"""Security + access-control tests for crm_app.

Run: bench --site <site> run-tests --app crm_app
(the site needs allow_tests=1)
"""

import base64

import frappe
from frappe.tests.utils import FrappeTestCase

from crm_app.api import validate_upload

def _valid_png() -> bytes:
	"""A genuinely valid PNG, generated by Pillow so it passes the same decode check."""
	from io import BytesIO

	from PIL import Image

	buf = BytesIO()
	Image.new("RGB", (4, 4), (12, 34, 56)).save(buf, format="PNG")
	return buf.getvalue()


_PNG = _valid_png()


class TestUploadSecurity(FrappeTestCase):
	def test_blocks_dangerous_extension(self):
		with self.assertRaises(frappe.ValidationError):
			validate_upload("evil.exe", b"whatever", max_mb=5)

	def test_blocks_renamed_executable_as_image(self):
		# .png name but Windows PE (MZ) bytes — must be rejected by signature sniffing.
		with self.assertRaises(frappe.ValidationError):
			validate_upload("photo.png", b"MZ\x90\x00\x03" + b"\x00" * 50, images_only=True, max_mb=5)

	def test_blocks_empty(self):
		with self.assertRaises(frappe.ValidationError):
			validate_upload("a.png", b"", images_only=True)

	def test_accepts_valid_png(self):
		# Should not raise.
		validate_upload("ok.png", _PNG, images_only=True, max_mb=5)


def _make_rep(email):
	from crm_app import dev_seed

	company = dev_seed._ensure_company()
	for g in ("Male", "Female"):
		if not frappe.db.exists("Gender", g):
			frappe.get_doc({"doctype": "Gender", "gender": g}).insert(ignore_permissions=True)
	if not frappe.db.exists("User", email):
		frappe.get_doc(
			{
				"doctype": "User",
				"email": email,
				"first_name": email.split("@")[0],
				"send_welcome_email": 0,
				"roles": [{"role": "Sales User"}],
			}
		).insert(ignore_permissions=True)
	emp = frappe.db.get_value("Employee", {"user_id": email}, "name")
	if not emp:
		emp = frappe.get_doc(
			{
				"doctype": "Employee",
				"first_name": email.split("@")[0],
				"user_id": email,
				"company": company,
				"status": "Active",
				"gender": "Male",
				"date_of_birth": "1990-01-01",
				"date_of_joining": "2022-01-01",
			}
		).insert(ignore_permissions=True).name
	return emp


class TestVisitAccessControl(FrappeTestCase):
	@classmethod
	def setUpClass(cls):
		super().setUpClass()
		cls.rep_a = _make_rep("repa@crmtest.local")
		cls.rep_b = _make_rep("repb@crmtest.local")
		# A visit owned by rep A
		v = frappe.get_doc(
			{
				"doctype": "CRM Visit",
				"sales_person": cls.rep_a,
				"visit_date": frappe.utils.today(),
				"party_type": "Prospect",
				"prospect_name": "Access Test Shop",
				"visit_purpose": "Follow-up",
				"visit_status": "Completed",
			}
		).insert(ignore_permissions=True)
		cls.visit_a = v.name
		frappe.db.commit()

	def tearDown(self):
		frappe.set_user("Administrator")

	def test_owner_can_read_own_visit(self):
		from crm_app import field_visit

		frappe.set_user("repa@crmtest.local")
		data = field_visit.get_visit(self.visit_a)
		self.assertEqual(data["visit"]["sales_person"], self.rep_a)

	def test_other_rep_cannot_read_visit(self):
		from crm_app import field_visit

		frappe.set_user("repb@crmtest.local")
		with self.assertRaises(frappe.PermissionError):
			field_visit.get_visit(self.visit_a)

	def test_my_visits_scoped_to_session(self):
		from crm_app import field_visit

		frappe.set_user("repb@crmtest.local")
		names = [r["name"] for r in field_visit.get_my_visits()]
		self.assertNotIn(self.visit_a, names)
